"""测试向量：标准测试数据集中管理。"""

TEST_VECTORS = {
    "Base64": [
        {
            "name": "Base64 encode 'hello'",
            "operation": "encode",
            "input": "hello",
            "encoding": "text",
            "output": "text",
            "expected_field": "base64",
            "expected": "aGVsbG8=",
        },
        {
            "name": "Base64 encode '中文'",
            "operation": "encode",
            "input": "中文",
            "encoding": "text",
            "output": "text",
            "expected_field": "base64",
            "expected": "5Lit5paH",
        },
        {
            "name": "Base64 decode 'aGVsbG8='",
            "operation": "decode",
            "input": "aGVsbG8=",
            "encoding": "text",
            "output": "text",
            "expected_field": "data",
            "expected": "hello",
        },
    ],
    "UTF-8": [
        {
            "name": "UTF-8 encode 'ABC'",
            "operation": "encode",
            "input": "ABC",
            "output": "hex",
            "expected_field": "data",
            "expected": "414243",
        },
        {
            "name": "UTF-8 encode '中文'",
            "operation": "encode",
            "input": "中文",
            "output": "hex",
            "expected_field": "data",
            "expected": "e4b8ade69687",
        },
        {
            "name": "UTF-8 decode hex 'e4b8ade69687'",
            "operation": "decode",
            "input": "e4b8ade69687",
            "encoding": "hex",
            "output": "text",
            "expected_field": "data",
            "expected": "中文",
        },
    ],
    "SHA-256": [
        {
            "name": "SHA256('abc')",
            "operation": "digest",
            "input": "616263",
            "encoding": "hex",
            "output": "hex",
            "expected_field": "digest",
            "expected": "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
        },
        {
            "name": "SHA256('')",
            "operation": "digest",
            "input": "",
            "encoding": "text",
            "output": "hex",
            "expected_field": "digest",
            "expected": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        },
        {
            "name": "SHA256('abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq')",
            "operation": "digest",
            "input": "abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq",
            "encoding": "text",
            "output": "hex",
            "expected_field": "digest",
            "expected": "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1",
        },
    ],
}
