"""测试向量：标准测试数据集中管理。"""

TEST_VECTORS = {
    "Base64": [
        {
            "name": "Base64 encode 'hello'",
            "operation": "encode",
            "input": "hello",
            "encoding": "text",
            "output": "text",
            "expected_field": "base64",
            "expected": "aGVsbG8=",
        },
        {
            "name": "Base64 encode '中文'",
            "operation": "encode",
            "input": "中文",
            "encoding": "text",
            "output": "text",
            "expected_field": "base64",
            "expected": "5Lit5paH",
        },
        {
            "name": "Base64 decode 'aGVsbG8='",
            "operation": "decode",
            "input": "aGVsbG8=",
            "encoding": "text",
            "output": "text",
            "expected_field": "data",
            "expected": "hello",
        },
    ],
    "UTF-8": [
        {
            "name": "UTF-8 encode 'ABC'",
            "operation": "encode",
            "input": "ABC",
            "output": "hex",
            "expected_field": "data",
            "expected": "414243",
        },
        {
            "name": "UTF-8 encode '中文'",
            "operation": "encode",
            "input": "中文",
            "output": "hex",
            "expected_field": "data",
            "expected": "e4b8ade69687",
        },
        {
            "name": "UTF-8 decode hex 'e4b8ade69687'",
            "operation": "decode",
            "input": "e4b8ade69687",
            "encoding": "hex",
            "output": "text",
            "expected_field": "data",
            "expected": "中文",
        },
    ],
    "SHA-256": [
        {
            "name": "SHA256('abc')",
            "operation": "digest",
            "input": "616263",
            "encoding": "hex",
            "output": "hex",
            "expected_field": "digest",
            "expected": "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
        },
        {
            "name": "SHA256('')",
            "operation": "digest",
            "input": "",
            "encoding": "text",
            "output": "hex",
            "expected_field": "digest",
            "expected": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        },
    ],
    "SHA-1": [
        {
            "name": "SHA1('abc')",
            "operation": "digest",
            "input": "616263",
            "encoding": "hex",
            "output": "hex",
            "expected_field": "digest",
            "expected": "a9993e364706816aba3e25717850c26c9cd0d89d",
        },
        {
            "name": "SHA1('')",
            "operation": "digest",
            "input": "",
            "encoding": "text",
            "output": "hex",
            "expected_field": "digest",
            "expected": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
        },
    ],
    "SHA-3": [
        {
            "name": "SHA3-256('abc')",
            "operation": "digest",
            "input": "616263",
            "encoding": "hex",
            "output": "hex",
            "expected_field": "digest",
            "expected": "3a985da74fe225b2045c172d6bd390bd855f086e3e9d525b46bfe24511431532",
        },
    ],
    "RIPEMD-160": [
        {
            "name": "RIPEMD160('abc')",
            "operation": "digest",
            "input": "616263",
            "encoding": "hex",
            "output": "hex",
            "expected_field": "digest",
            "expected": "8eb208f7e05d987a9b044a8e98c6b087f15a0bfc",
        },
    ],
    "AES": [
        {
            "name": "AES-128 ECB encrypt (FIPS 197 App.B)",
            "operation": "encrypt",
            "input": "6bc1bee22e409f96e93d7e117393172a",
            "key": "2b7e151628aed2a6abf7158809cf4f3c",
            "mode": "ECB",
            "padding": "none",
            "output": "hex",
            "expected_field": "ciphertext",
            "expected": "3ad77bb40d7a3660a89ecaf32466ef97",
        },
        {
            "name": "AES-128 ECB decrypt (FIPS 197 App.B)",
            "operation": "decrypt",
            "input": "3ad77bb40d7a3660a89ecaf32466ef97",
            "key": "2b7e151628aed2a6abf7158809cf4f3c",
            "mode": "ECB",
            "padding": "none",
            "output": "hex",
            "expected_field": "plaintext",
            "expected": "6bc1bee22e409f96e93d7e117393172a",
        },
    ],
    "HMAC": [
        {
            "name": "HMAC-SHA256 (RFC 4231 TC2)",
            "operation": "compute",
            "algorithm": "HmacSHA256",
            "key": "0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b",
            "data": "4869205468657265",
            "output": "hex",
            "expected_field": "mac",
            "expected": "b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7",
        },
    ],
    "PBKDF2": [
        {
            "name": "PBKDF2-HMAC-SHA256 (password/salt/1)",
            "operation": "derive",
            "password": "70617373776f7264",
            "salt": "73616c74",
            "iterations": 1,
            "dk_len": 32,
            "prf": "HmacSHA256",
            "output": "hex",
            "expected_field": "derived_key",
            "expected": "120fb6cffcf8b32c43e7225256c4f837a86548c92ccc35480805987cb70be17b",
        },
    ],
    "RSA": [
        {
            "name": "RSA keygen + sign + verify",
            "operation": "keygen_sign_verify",
            "bits": 512,
            "data": "68656c6c6f",
            "encoding": "hex",
            "hash_algo": "sha256",
            "expected_field": "self_consistent",
            "expected": True,
        },
    ],
    "RSA-SHA1": [
        {
            "name": "RSA-SHA1 keygen + sign + verify",
            "operation": "keygen_sign_verify",
            "bits": 512,
            "data": "68656c6c6f",
            "encoding": "hex",
            "expected_field": "self_consistent",
            "expected": True,
        },
    ],
    "ECC": [
        {
            "name": "ECC keygen + point on curve",
            "operation": "keygen_verify_point",
            "expected_field": "on_curve",
            "expected": True,
        },
    ],
    "ECDSA": [
        {
            "name": "ECDSA keygen + sign + verify",
            "operation": "keygen_sign_verify",
            "data": "68656c6c6f",
            "encoding": "hex",
            "hash_algo": "sha256",
            "expected_field": "self_consistent",
            "expected": True,
        },
    ],
}
